import 'shared/nashorn-polyfills';
import './area';
import './area/asgarnia';
import './area/events';
import './area/feldip-hills';
import './area/guilds';
import './chat';
import './npcs/kandarin';
import './widget/settings';