
//NOTE: This should be kept in-sync with ChannelType.java
export enum MesType {
    GAME = 0,
	PUBLIC = 1,
	PUBLIC_UNFILTERABLE = 2,
	PUBLIC_QUICKCHAT = 17,
	PRIVATE = 3,
	PRIVATE_SYSTEM = 4,
	PRIVATE_ECHO = 6,
	PRIVATE_UNFILTERABLE = 7,
	FRIENDCHANNEL = 9,
	FRIENDCHANNEL_SYSTEM = 11,
	PRIVATE_QUICKCHAT = 18,
	PRIVATE_ECHO_QUICKCHAT = 19,
	FRIENDCHANNEL_QUICKCHAT = 20,
	GROUPCHANNEL_TEAM = 22,
	GROUPCHANNEL_TEAM_QUICKCHAT = 23,
	GROUPCHANNEL = 24,
	GROUPCHANNEL_QUICKCHAT = 25,
	CLANCHANNEL = 41,
	CLANCHANNEL_QUICKCHAT = 42,
	CLANCHANNEL_SYSTEM = 43,
	CLANCHANNEL_GUEST = 44,
	CLANCHANNEL_GUEST_QUICKCHAT = 45,
	CLANCHANNEL_GUEST_SYSTEM = 46,
	CONSOLE = 99,
	TRADE = 100,
	REQUEST = 101,
	ASSIST = 102,

	/**
	 * Represents a game message which can be filtered by players
	 */
	GAME_SPAM = 109,

	/**
	 * Represents a clan invitation message
	 */
	CLAN_INVITE = 117,
	BROADCAST = 125
}
